<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PuxDesignFileWatcher.Application\PuxDesignFileWatcher.Application.csproj" />
    <ProjectReference Include="..\PuxDesignFileWatcher.Domain\PuxDesignFileWatcher.Domain.csproj" />
  </ItemGroup>

</Project>
