@PuxDesignFileWatcher.Api_HostAddress = https://localhost:44308

POST {{PuxDesignFileWatcher.Api_HostAddress}}/api/analysis
Content-Type: application/json
Accept: application/json

{
  "rootPath": "C:\\Logs"
}

###
