<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PuxDesignFileWatcher.Application\PuxDesignFileWatcher.Application.csproj" />
    <ProjectReference Include="..\PuxDesignFileWatcher.Infrastructure\PuxDesignFileWatcher.Infrastructure.csproj" />
  </ItemGroup>

</Project>
